[2024-07-13 21:16:14,568: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-13 21:16:14,572: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 21:16:14,582: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 21:16:14,583: INFO: common: created directory at: artifacts]
[2024-07-13 21:16:14,584: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-13 21:16:17,390: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: A9DD:A79DA:7DA34:AB85D:66928280
Accept-Ranges: bytes
Date: Sat, 13 Jul 2024 15:46:16 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10238-MAA
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1720885576.776769,VS0,VE296
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 8766c795ef5292c8944d516da43308217e951b40
Expires: Sat, 13 Jul 2024 15:51:16 GMT
Source-Age: 0

]
[2024-07-13 21:16:17,825: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-13 21:16:17,826: INFO: main: *******************]
[2024-07-13 21:16:17,826: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-13 21:16:17,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 21:16:17,833: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 21:16:17,833: INFO: common: created directory at: artifacts]
[2024-07-13 21:16:17,834: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-13 21:16:28,197: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-13 21:16:28,437: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-13 21:16:28,437: INFO: main: *******************]
[2024-07-13 21:16:28,437: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-13 21:16:28,440: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 21:16:28,443: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 21:16:29,143: INFO: common: created directory at: artifacts]
[2024-07-13 21:16:29,145: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2024-07-13 21:16:29,145: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2024-07-13 21:16:29,146: INFO: common: created directory at: artifacts\training]
[2024-07-13 21:17:13,579: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-13 21:17:13,580: INFO: main: *******************]
[2024-07-13 21:17:13,580: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-13 21:17:13,584: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 21:17:13,587: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 21:17:13,587: INFO: common: created directory at: artifacts]
[2024-07-13 21:17:26,394: INFO: common: json file saved at: scores.json]
[2024-07-13 21:17:26,395: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-13 21:21:46,427: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 21:21:46,433: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 21:21:46,435: INFO: common: created directory at: artifacts]
[2024-07-13 21:21:46,436: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-13 21:21:46,437: INFO: 1170291011: File already exists of size: ~ 11345 KB]
[2024-07-13 21:22:08,300: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 21:22:08,306: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 21:22:08,307: INFO: common: created directory at: artifacts]
[2024-07-13 21:22:08,309: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-13 21:22:08,786: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-13 21:22:17,088: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 21:22:17,093: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 21:22:17,096: INFO: common: created directory at: artifacts]
[2024-07-13 21:22:17,098: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2024-07-13 21:22:17,100: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2024-07-13 21:22:23,318: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 21:22:23,324: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 21:22:23,326: INFO: common: created directory at: artifacts]
[2024-07-13 21:22:23,330: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2024-07-13 21:22:23,331: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2024-07-13 21:22:23,334: INFO: common: created directory at: artifacts\training]
[2024-07-13 21:23:00,601: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 21:23:00,605: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 21:23:00,607: INFO: common: created directory at: artifacts]
[2024-07-13 21:23:20,319: INFO: common: json file saved at: scores.json]
[2024-07-13 21:29:10,404: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 21:29:10,411: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 21:29:10,414: INFO: common: created directory at: artifacts]
[2024-07-13 21:29:24,402: INFO: common: json file saved at: scores.json]
[2024-07-13 22:58:24,620: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-13 22:58:24,622: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 22:58:24,623: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 22:58:24,625: INFO: common: created directory at: artifacts]
[2024-07-13 22:58:24,625: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-13 22:58:28,641: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 7DA0:A30CC:A097D:D9BF4:6692B939
Accept-Ranges: bytes
Date: Sat, 13 Jul 2024 17:28:27 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10227-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1720891705.309464,VS0,VE1944
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 5f5d03a70c2b92507b1e090c1345871cfcf979a1
Expires: Sat, 13 Jul 2024 17:33:27 GMT
Source-Age: 2

]
[2024-07-13 22:58:28,907: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-13 22:58:28,907: INFO: main: *******************]
[2024-07-13 22:58:28,907: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-13 22:58:28,909: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 22:58:28,911: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 22:58:28,911: INFO: common: created directory at: artifacts]
[2024-07-13 22:58:28,912: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-13 22:58:29,271: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-13 22:58:29,419: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-13 22:58:29,419: INFO: main: *******************]
[2024-07-13 22:58:29,419: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-13 22:58:29,422: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 22:58:29,424: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 22:58:29,424: INFO: common: created directory at: artifacts]
[2024-07-13 22:58:29,424: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2024-07-13 22:58:29,426: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2024-07-13 22:58:29,426: INFO: common: created directory at: artifacts\training]
[2024-07-13 22:58:59,627: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-13 22:58:59,628: INFO: main: *******************]
[2024-07-13 22:58:59,628: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-13 22:58:59,630: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-13 22:58:59,632: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-13 22:58:59,632: INFO: common: created directory at: artifacts]
[2024-07-13 22:59:09,962: INFO: common: json file saved at: scores.json]
[2024-07-13 22:59:09,962: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-15 22:59:05,642: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-15 22:59:05,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-15 22:59:05,652: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-15 22:59:05,653: INFO: common: created directory at: artifacts]
[2024-07-15 22:59:05,653: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-15 22:59:05,654: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2024-07-15 22:59:06,074: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-15 22:59:29,994: INFO: stage_02_prepare_base_model: *******************]
[2024-07-15 22:59:29,995: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-15 22:59:29,999: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-15 22:59:30,002: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-15 22:59:30,003: INFO: common: created directory at: artifacts]
[2024-07-15 22:59:30,004: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-15 22:59:30,906: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-15 22:59:31,176: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-15 22:59:41,038: INFO: stage_03_training: *******************]
[2024-07-15 22:59:41,039: INFO: stage_03_training: >>>>>> stage Training started <<<<<<]
[2024-07-15 22:59:41,043: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-15 22:59:41,045: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-15 22:59:41,046: INFO: common: created directory at: artifacts]
[2024-07-15 22:59:41,046: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2024-07-15 22:59:41,047: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2024-07-15 22:59:41,048: INFO: common: created directory at: artifacts\training]
[2024-07-15 23:00:20,386: INFO: stage_03_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-15 23:00:28,057: INFO: stage_04_evaluation: *******************]
[2024-07-15 23:00:28,057: INFO: stage_04_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-15 23:00:28,063: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-15 23:00:28,072: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-15 23:00:28,072: INFO: common: created directory at: artifacts]
[2024-07-15 23:00:40,062: INFO: common: json file saved at: scores.json]
[2024-07-15 23:00:40,063: INFO: stage_04_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-15 23:36:21,594: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.0.103:80]
[2024-07-15 23:36:21,595: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-15 23:36:49,384: INFO: _internal: 127.0.0.1 - - [15/Jul/2024 23:36:49] "GET / HTTP/1.1" 200 -]
[2024-07-15 23:38:23,727: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\user\Documents\project_dl\Chicken-Disease-Classification--Project\app.py", line 41, in predictRoute
    result = clApp.classifier.predict()
AttributeError: 'ClientApp' object has no attribute 'classifier'
[2024-07-15 23:38:23,763: INFO: _internal: 127.0.0.1 - - [15/Jul/2024 23:38:23] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-15 23:39:22,243: INFO: _internal: 127.0.0.1 - - [15/Jul/2024 23:39:22] "GET / HTTP/1.1" 200 -]
[2024-07-15 23:39:30,851: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\user\Documents\project_dl\Chicken-Disease-Classification--Project\app.py", line 41, in predictRoute
    result = clApp.classifier.predict()
AttributeError: 'ClientApp' object has no attribute 'classifier'
[2024-07-15 23:39:30,854: INFO: _internal: 127.0.0.1 - - [15/Jul/2024 23:39:30] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-15 23:42:02,773: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-15 23:42:02,789: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-15 23:42:02,799: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-15 23:42:02,800: INFO: common: created directory at: artifacts]
[2024-07-15 23:42:02,800: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-15 23:42:02,801: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2024-07-15 23:42:03,195: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-15 23:42:03,195: INFO: main: *******************]
[2024-07-15 23:42:03,196: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-15 23:42:03,199: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-15 23:42:03,202: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-15 23:42:03,202: INFO: common: created directory at: artifacts]
[2024-07-15 23:42:03,203: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-15 23:42:04,022: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-15 23:42:04,303: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-15 23:42:04,304: INFO: main: *******************]
[2024-07-15 23:42:04,304: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-15 23:42:04,309: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-15 23:42:04,311: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-15 23:42:04,312: INFO: common: created directory at: artifacts]
[2024-07-15 23:42:04,312: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2024-07-15 23:42:04,312: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2024-07-15 23:42:04,313: INFO: common: created directory at: artifacts\training]
[2024-07-15 23:42:41,955: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-15 23:42:41,956: INFO: main: *******************]
[2024-07-15 23:42:41,956: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-15 23:42:41,959: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-15 23:42:41,961: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-15 23:42:41,962: INFO: common: created directory at: artifacts]
[2024-07-15 23:42:53,949: INFO: common: json file saved at: scores.json]
[2024-07-15 23:42:53,949: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-16 12:13:26,141: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-16 12:13:26,151: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-16 12:13:26,162: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-16 12:13:26,163: INFO: common: created directory at: artifacts]
[2024-07-16 12:13:26,163: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-16 12:13:26,164: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2024-07-16 12:13:26,512: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-16 12:13:26,512: INFO: main: *******************]
[2024-07-16 12:13:26,512: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-16 12:13:26,516: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-16 12:13:26,518: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-16 12:13:26,518: INFO: common: created directory at: artifacts]
[2024-07-16 12:13:26,519: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-16 12:13:27,181: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-16 12:13:27,546: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-16 12:13:27,547: INFO: main: *******************]
[2024-07-16 12:13:27,547: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-07-16 12:13:27,553: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-16 12:13:27,556: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-16 12:13:27,558: INFO: common: created directory at: artifacts]
[2024-07-16 12:13:27,558: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2024-07-16 12:13:27,558: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2024-07-16 12:13:27,559: INFO: common: created directory at: artifacts\training]
[2024-07-16 12:14:09,215: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-16 12:14:09,215: INFO: main: *******************]
[2024-07-16 12:14:09,215: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-16 12:14:09,218: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-16 12:14:09,220: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-16 12:14:09,221: INFO: common: created directory at: artifacts]
[2024-07-16 12:14:20,803: INFO: common: json file saved at: scores.json]
[2024-07-16 12:14:20,804: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-16 12:21:35,160: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-07-16 12:21:35,161: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-16 12:21:57,561: INFO: _internal: 127.0.0.1 - - [16/Jul/2024 12:21:57] "GET / HTTP/1.1" 200 -]
[2024-07-16 12:22:59,534: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\user\Documents\project_dl\Chicken-Disease-Classification--Project\app.py", line 65, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\user\Documents\project_dl\Chicken-Disease-Classification--Project\app.py", line 15, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"))
NameError: name 'load_model' is not defined
[2024-07-16 12:22:59,573: INFO: _internal: 127.0.0.1 - - [16/Jul/2024 12:22:59] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-16 12:24:40,843: INFO: _internal: 192.168.0.103 - - [16/Jul/2024 12:24:40] "GET / HTTP/1.1" 200 -]
[2024-07-16 12:24:49,531: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\user\Documents\project_dl\Chicken-Disease-Classification--Project\app.py", line 65, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\user\Documents\project_dl\Chicken-Disease-Classification--Project\app.py", line 15, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"))
NameError: name 'load_model' is not defined
[2024-07-16 12:24:49,533: INFO: _internal: 192.168.0.103 - - [16/Jul/2024 12:24:49] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-16 12:25:23,003: INFO: _internal: 192.168.0.103 - - [16/Jul/2024 12:25:23] "GET / HTTP/1.1" 200 -]
[2024-07-16 12:25:30,403: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\user\Documents\project_dl\Chicken-Disease-Classification--Project\app.py", line 65, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\user\Documents\project_dl\Chicken-Disease-Classification--Project\app.py", line 15, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"))
NameError: name 'load_model' is not defined
[2024-07-16 12:25:30,405: INFO: _internal: 192.168.0.103 - - [16/Jul/2024 12:25:30] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-07-16 12:25:33,957: INFO: _internal: 127.0.0.1 - - [16/Jul/2024 12:25:33] "GET / HTTP/1.1" 200 -]
[2024-07-16 12:25:41,683: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\user\Documents\project_dl\Chicken-Disease-Classification--Project\app.py", line 65, in predictRoute
    result = clApp.classifier.predict()
  File "C:\Users\user\Documents\project_dl\Chicken-Disease-Classification--Project\app.py", line 15, in predict
    model = load_model(os.path.join("artifacts","training", "model.h5"))
NameError: name 'load_model' is not defined
[2024-07-16 12:25:41,685: INFO: _internal: 127.0.0.1 - - [16/Jul/2024 12:25:41] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
